------------------------
analysis_flowchart.png

@startuml

skinparam ConditionEndStyle hline
skinparam FontStyle mono


if (Use demo data) then (<color:#b7410e> Yes</color>)
    :<color:#008000>npx1_data uploaded</color>;
else (<color:#008000> No</color>)
    :<color:#008000>Data upload</color>;
endif 


switch(<color:#FF0000>Outlier Detection</color>)
case ()
    :olink_qc_plot;
case () 
    :olink_pca_plot;
case ()
    :olink_umap_plot;
endswitch

switch (<color:#FFA500>Filter Data</color>)
case (<color:#b7410e> Yes</color>)
  : Filter sample(s) and/or Assay(s);
case (<color:#008000> No</color>)
  : Unfiltered data;
endswitch 


switch(<color:#5067ed>Statistical analysis</color>)
    case(<color:#3910ee> Outcome factor with 2 levels</color>) 
        switch(<color:#1c1c84>Parametric</color>)
            case (<color:#b7410e> Yes</color>)
            :olink_ttest;
            detach
            case (<color:#008000> No</color>)
            :olink_wilcox;
            detach
        endswitch
    case (<color:#b7410e>Outcome factor > 2 levels</color>)
        switch(<color:#1c1c84>Parametric</color>)
            case (<color:#b7410e> Yes</color>)
                switch()
                    case()
                        :olink_anova;
                        :<color:#b7410e>olink_anova_posthoc</color>;
                        detach
                    case()
                        :olink_lmer;
                        :<color:#b7410e>olink_lmer_posthoc</color>;
                        detach
                endswitch
            case (<color:#008000> No</color>)
                switch()
                    case()            
                        :olink_one_non_parametric;
                        :<color:#008000> olink_one_non_parametric_posthoc</color>;
                        detach
                    case()
                        :olink_ordinalRegression; 
                        :<color:#008000> olink_ordinalRegression_posthoc</color>;
                        detach
                endswitch
        endswitch
endswitch


@enduml 

PlantUML version 1.2025.1(Tue Jan 07 18:35:36 CET 2025)
(GPL source distribution)
Java Runtime: OpenJDK Runtime Environment
JVM: OpenJDK 64-Bit Server VM
Default Encoding: UTF-8
Language: en
Country: US

------------------------
