@startuml

start

if (Demo Data?) then (yes)
    :<color:#008000>npx1_data uploaded</color>;
else (no)
    :<color:#008000>Data Upload</color>;
endif

' Merge paths directly into Outlier Detection (NO extra diamond)
-> <color:#FF0000>Outlier Detection?</color>;

switch (Method)
case ("QC Plot")
  :olink_qc_plot;
case ("PCA Plot") 
  :olink_pca_plot;
case ("UMAP Plot")
  :olink_umap_plot;
endswitch

@enduml




' <color:#FF0099>Olink_qc_plot</color>;
' <color:#FFA500>Filter Data</color>;
' <color:#FF9900>Olink_pca_plot</color>;
' <color:#FFA500>Filter Data</color>;
' <color:#F9000>Olink_umap_plot</color>;
' <color:#FFA500>Filter Data</color>;
' <color:#008000>Statistics</color>;
' <color:#800080>Posthoc Statistics</color>;
' <color:#0000FF>Pathway Enrichment</color>;
' <color:#006A4E>Additional Visualization</color>;


' @startuml

' : <color:#008000>Data Upload</color>;
' : <color:#FF0000>Outlier Detection</color>;
' : <color:#FFA500>Filter Data</color>;
' : <color:#008000>Statistics</color>;
' : <color:#800080>Posthoc Statistics</color>;
' : <color:#0000FF>Pathway Enrichment</color>;
' : <color:#006A4E>Additional Visualization</color>;
' @enduml